## Importing Packages

In [1]:
import geopandas as gpd
from shapely import wkt

## Loading Data

In [2]:
school_df = gpd.read_file('../../data/secondary_data/Lawrence_schools.csv')

In [3]:
school_df.head()

,OBJECTID,SCHID,NAME,ADDRESS,TOWN_MAIL,TOWN,ZIPCODE,PHONE,GRADES,TYPE,TYPE_DESC,TYPE_DESC2,DIST_NAME,DIST_CODE,MA_ADDR_ID,geometry
0,62,01490020,James F Hennessey School,122 Hancock Street,Lawrence,LAWRENCE,01841,978-975-5950,"PK,K,01,02",ELE,Public Elementary,,Lawrence,01490000,2111326,POINT (226453.2704000026 938544.6402000003)
1,20,01490040,Francis M Leahy School,100 Erving Avenue,Lawrence,LAWRENCE,01841,978-975-5959,"01,02,03,04,05",ELE,Public Elementary,,Lawrence,01490000,2113402,POINT (227723.89840000123 940507.9697999991)
2,194,04540205,Lawrence Family Development Charter School,34 West Street,Lawrence,LAWRENCE,01841,978-689-9863,"PK,K,01,02,03,04,05,06,07,08",CHA,Charter,,Lawrence Family Development Charter,04540000,2119645,POINT (226715.9219999984 939816.4981999993)
3,201,01490537,School for Exceptional Studies,233 Haverhill Street,Lawrence,LAWRENCE,01841,978-975-5980,"K,01,02,03,04,05,06,07,08,09,10,11,12",SEC,Public Secondary,,Lawrence,01490000,2115829,POINT (227558.6675999984 940054.0148000009)
4,264,01490027,Parthum Middle School,255 East Haverhill Street,Lawrence,LAWRENCE,01841,978-691-7224,"05,06,07,08",MID,Public Middle,,Lawrence,01490000,2113286,POINT (229223.8845999986 940918.4127999991)

In [4]:
# Convert WKT text to shapely geometry objects
school_df["geometry"] = school_df["geometry"].apply(wkt.loads)

# Create GeoDataFrame with correct CRS
school_gdf = gpd.GeoDataFrame(school_df, geometry="geometry", crs="EPSG:26986")

# Convert to lat/lon (WGS84)
school_gdf = school_gdf.to_crs(epsg=4326)

# Extract latitude & longitude
school_gdf["longitude"] = school_gdf.geometry.x
school_gdf["latitude"] = school_gdf.geometry.y

school_gdf[["latitude", "longitude"]].head()

    latitude  longitude
0  42.697041 -71.177165
1  42.714670 -71.161563
2  42.708481 -71.173900
3  42.710589 -71.163602
4  42.718310 -71.143231

In [5]:
school_gdf.columns

Index(['OBJECTID', 'SCHID', 'NAME', 'ADDRESS', 'TOWN_MAIL', 'TOWN', 'ZIPCODE',
       'PHONE', 'GRADES', 'TYPE', 'TYPE_DESC', 'TYPE_DESC2', 'DIST_NAME',
       'DIST_CODE', 'MA_ADDR_ID', 'geometry', 'longitude', 'latitude'],
      dtype='object')

In [6]:
school_gdf[['OBJECTID', 'SCHID', 'NAME', 'ADDRESS', 'TOWN_MAIL', 'TOWN', 'ZIPCODE',
       'PHONE', 'GRADES', 'TYPE', 'TYPE_DESC', 'DIST_NAME', 'longitude', 'latitude']].to_csv('../../streamlit-app/school_geocoded.csv', index = None)

## Places of Worship

In [7]:
worship_df = gpd.read_file('../../data/secondary_data/places_of_worship.csv')

In [8]:
worship_df.head()

,NAME,ADDRESS,CITY,GEOG_CITY,ZIPCODE,TELEPHONE,EMAIL,WEBSITE,MAIL_ADDR,LEADERSHIP,YEAR_EST,DENOM,ORG,TYPE,SOURCE,MAD_ID,geometry
0,Congregation Ansha Sholum,411 Hampshire Street,Lawrence,Lawrence,01842,978-683-4544,AnshaShulim@prodigy.net,,P.O. Box 1045,,1919,,,Synagogue,Synagogue Council of Massachusetts,2115464,POINT (226943.80170000345 940628.4769000001)
1,Third Baptist Church,22 Warren Street,Lawrence,Lawrence,01841,978-682-9913,,http://thirdbaptistchurchlawrence.org,,Lewis Floyd,1904,American Baptist Church,Merrimack Valley Baptist Association,Church,Massachusetts Council of Churches,2123993,POINT (226460.45069999993 939105.2637999989)
2,First Haitian Baptist Church,115 Garden Street,Lawrence,Lawrence,01841,978-332-1642,,,"c/o Camille, 14 Highlawn Avenue, Lawrence, MA ...",Pascal Camille,1994,American Baptist Church,Merrimack Valley Baptist Association,Church,Massachusetts Council of Churches,2119725,POINT (228328.43079999834 939921.8553000018)
3,Iglesia Bautista Hispana,492 Lowell Street,Lawrence,Lawrence,01844,978-794-2523,ibhdelawrence@gmail.com,,,Jose Reye,1990,American Baptist Church,Merrimack Valley Baptist Association,Church,Massachusetts Council of Churches,2061273,POINT (222975.60849999636 939004.4232000001)
4,Corpus Christi,35 Essex Street,Lawrence,Lawrence,01840,978-685-1711,ic@corpuschristilawrence.org,http://www.corpuschristilawrence.org/,,Rev. Francis X. Mawn,2004,Roman Catholic,Archdiocese of Boston,Church,Archdiocese of Boston,2108829,POINT (228352.02830000222 939767.3172999993)

In [9]:
# Convert WKT text to shapely geometry objects
worship_df["geometry"] = worship_df["geometry"].apply(wkt.loads)

# Create GeoDataFrame with correct CRS
wor_gdf = gpd.GeoDataFrame(worship_df, geometry="geometry", crs="EPSG:26986")

# Convert to lat/lon (WGS84)
wor_gdf = wor_gdf.to_crs(epsg=4326)

# Extract latitude & longitude
wor_gdf["longitude"] = wor_gdf.geometry.x
wor_gdf["latitude"] = wor_gdf.geometry.y

wor_gdf[["latitude", "longitude"]].head()

    latitude  longitude
0  42.715782 -71.171080
1  42.702087 -71.177051
2  42.709372 -71.154212
3  42.701290 -71.219587
4  42.707980 -71.153932

In [10]:
wor_gdf.columns

Index(['NAME', 'ADDRESS', 'CITY', 'GEOG_CITY', 'ZIPCODE', 'TELEPHONE', 'EMAIL',
       'WEBSITE', 'MAIL_ADDR', 'LEADERSHIP', 'YEAR_EST', 'DENOM', 'ORG',
       'TYPE', 'SOURCE', 'MAD_ID', 'geometry', 'longitude', 'latitude'],
      dtype='object')

In [11]:
wor_gdf[['NAME', 'ADDRESS', 'CITY', 'GEOG_CITY', 'ZIPCODE', 'LEADERSHIP', 'YEAR_EST', 'DENOM', 'ORG',
       'TYPE', 'SOURCE',  'geometry', 'longitude', 'latitude']].to_csv('../../streamlit-app/places_of_worship_geocoded.csv', index = None)

In [12]:

wor_gdf.head()

,NAME,ADDRESS,CITY,GEOG_CITY,ZIPCODE,TELEPHONE,EMAIL,WEBSITE,MAIL_ADDR,LEADERSHIP,YEAR_EST,DENOM,ORG,TYPE,SOURCE,MAD_ID,geometry,longitude,latitude
0,Congregation Ansha Sholum,411 Hampshire Street,Lawrence,Lawrence,01842,978-683-4544,AnshaShulim@prodigy.net,,P.O. Box 1045,,1919,,,Synagogue,Synagogue Council of Massachusetts,2115464,POINT (-71.17108 42.71578),-71.171080,42.715782
1,Third Baptist Church,22 Warren Street,Lawrence,Lawrence,01841,978-682-9913,,http://thirdbaptistchurchlawrence.org,,Lewis Floyd,1904,American Baptist Church,Merrimack Valley Baptist Association,Church,Massachusetts Council of Churches,2123993,POINT (-71.17705 42.70209),-71.177051,42.702087
2,First Haitian Baptist Church,115 Garden Street,Lawrence,Lawrence,01841,978-332-1642,,,"c/o Camille, 14 Highlawn Avenue, Lawrence, MA ...",Pascal Camille,1994,American Baptist Church,Merrimack Valley Baptist Association,Church,Massachusetts Council of Churches,2119725,POINT (-71.15421 42.70937),-71.154212,42.709372
3,Iglesia Bautista Hispana,492 Lowell Street,Lawrence,Lawrence,01844,978-794-2523,ibhdelawrence@gmail.com,,,Jose Reye,1990,American Baptist Church,Merrimack Valley Baptist Association,Church,Massachusetts Council of Churches,2061273,POINT (-71.21959 42.70129),-71.219587,42.701290
4,Corpus Christi,35 Essex Street,Lawrence,Lawrence,01840,978-685-1711,ic@corpuschristilawrence.org,http://www.corpuschristilawrence.org/,,Rev. Francis X. Mawn,2004,Roman Catholic,Archdiocese of Boston,Church,Archdiocese of Boston,2108829,POINT (-71.15393 42.70798),-71.153932,42.707980